CONFIG_TRACKPOINT_EXPONENTIAL=y
# I2C enable
CONFIG_I2C=y
CONFIG_SENSOR=y
CONFIG_I2C_NRFX=y
CONFIG_LOG=y

# Trackpoint Sensitivity and Base Speed
CONFIG_TRACKPOINT_MOUSE_BASE_SPEED_PERCENT=70
CONFIG_TRACKPOINT_MOUSE_SENS_BASE_PERCENT=40

# Scroll tuning
CONFIG_TRACKPOINT_SCROLL_DIVISOR_SLOW=14
CONFIG_TRACKPOINT_SCROLL_DIVISOR_FAST=10
CONFIG_TRACKPOINT_SCROLL_INPUT_MAX=100

# Scroll direction inversion (non-natural scrolling)
CONFIG_TRACKPOINT_SCROLL_Y_DIR=-1
CONFIG_TRACKPOINT_SCROLL_X_DIR=-1