# I2C Trackpad
CONFIG_I2C=y
CONFIG_SENSOR=y
CONFIG_I2C_NRFX=y
CONFIG_LOG=y

# A320 Trackpad Sensitivity and Base Speed
CONFIG_A320_MOUSE_BASE_SPEED_PERCENT=150
CONFIG_A320_MOUSE_SENS_BASE_PERCENT=40

# Scroll tuning
CONFIG_A320_SCROLL_DIVISOR_SLOW=16
CONFIG_A320_SCROLL_DIVISOR_FAST=4


# Log via USB or Segger RTT
# CONFIG_ZMK_USB_LOGGING=y
# CONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=4000
