# .github/workflows/main.yml
name: Build ZMK firmware

on:
  pull_request:
  workflow_dispatch:
  push:
    paths-ignore:
      - "keymap-drawer/**"

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3.0

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    permissions:
      contents: write
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: firmware
          path: build-artifacts

      - name: Package Firmware into Zip
        run: |
          cd build-artifacts
          zip -r ../firmware.zip .

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: build-${{ github.run_number }}
          name: "Build ${{ github.run_number }}"
          draft: false
          prerelease: false
          files: |
            firmware.zip
